const data = [
  {
    id: 1,
    title: 'Darius',
    category: 'Fighters',
    img: '/images/RiotX_ChampionList_darius.jpg',
  },
  {
    id: 2,
    title: 'Aurelion Sol',
    category: 'Mages',
    img: '/images/RiotX_ChampionList_aurelionsol.jpg',
  },
  {
    id: 3,
    title: 'Zed',
    category: 'Assasins',
    img: '/images/RiotX_ChampionList_zed.jpg',
  },
  {
    id: 4,
    title: 'Garen',
    category: 'Tanks',
    img: '/images/RiotX_ChampionList_garen.jpg',
  },
  {
    id: 6,
    title: 'Caitlyn',
    category: 'Shooters',
    img: '/images/RiotX_ChampionList_caitlyn_v2.jpg',
  },
  {
    id: 7,
    title: 'Yasuo',
    category: 'Fighters',
    img: '/images/RiotX_ChampionList_yasuo.jpg',
  },
  {
    id: 8,
    title: 'Azir',
    category: 'Mages',
    img: '/images/RiotX_ChampionList_azir.jpg',
  },
  {
    id: 9,
    title: 'Braun',
    category: 'Supporters',
    img: '/images/RiotX_ChampionList_braun.jpg',
  },
  {
    id: 10,
    title: 'Nautilus',
    category: 'Tanks',
    img: '/images/RiotX_ChampionList_nautilus.jpg',
  },
  {
    id: 12,
    title: 'Draven',
    category: 'Shooters',
    img: '/images/RiotX_ChampionList_draven.jpg',
  },
  {
    id: 13,
    title: 'Viktor',
    category: 'Mages',
    img: '/images/RiotX_ChampionList_viktor.jpg',
  },
  {
    id: 14,
    title: 'Akali',
    category: 'Assasins',
    img: '/images/RiotX_ChampionList_akali.jpg',
  },
  {
    id: 15,
    title: 'Bardo',
    category: 'Supporters',
    img: '/images/RiotX_ChampionList_bard.jpg',
  },
  {
    id: 16,
    title: 'Camille',
    category: 'Fighters',
    img: '/images/RiotX_ChampionList_camille.jpg',
  },
  {
    id: 17,
    title: 'Galio',
    category: 'Tanks',
    img: '/images/RiotX_ChampionList_galio.jpg',
  },
  {
    id: 18,
    title: 'Gnar',
    category: 'Tanks',
    img: '/images/RiotX_ChampionList_gnar.jpg',
  },
  {
    id: 19,
    title: 'Jhin',
    category: 'Shooters',
    img: '/images/RiotX_ChampionList_jhin.jpg',
  },
  {
    id: 20,
    title: 'Karthus',
    category: 'Mages',
    img: '/images/RiotX_ChampionList_karthus.jpg',
  },
  {
    id: 21,
    title: 'Leona',
    category: 'Tanks',
    img: '/images/RiotX_ChampionList_leona.jpg',
  },
  {
    id: 22,
    title: 'Lux',
    category: 'Mages',
    img: '/images/RiotX_ChampionList_lux.jpg',
  },
  {
    id: 23,
    title: 'Yi',
    category: 'Assasins',
    img: '/images/RiotX_ChampionList_masteryi.jpg',
  },
  {
    id: 24,
    title: 'Miss Fortune',
    category: 'Shooters',
    img: '/images/RiotX_ChampionList_missfortune.jpg',
  },
  {
    id: 25,
    title: 'Mordekaiser',
    category: 'Tanks',
    img: '/images/RiotX_ChampionList_mordekaiser_v2.jpg',
  },
  {
    id: 26,
    title: 'Nasus',
    category: 'Tanks',
    img: '/images/RiotX_ChampionList_nasus.jpg',
  },
  {
    id: 27,
    title: 'Ornn',
    category: 'Tanks',
    img: '/images/RiotX_ChampionList_ornn.jpg',
  },
  {
    id: 28,
    title: 'Pantheon',
    category: 'Fighters',
    img: '/images/RiotX_ChampionList_pantheon.jpg',
  },
  {
    id: 29,
    title: 'Rakan',
    category: 'Supporters',
    img: '/images/RiotX_ChampionList_rakan.jpg',
  },
  {
    id: 30,
    title: 'Renekton',
    category: 'Fighters',
    img: '/images/RiotX_ChampionList_renekton.jpg',
  },
  {
    id: 31,
    title: 'Ryze',
    category: 'Mages',
    img: '/images/RiotX_ChampionList_ryze.jpg',
  },
  {
    id: 32,
    title: 'Shen',
    category: 'Tanks',
    img: '/images/RiotX_ChampionList_shen.jpg',
  },
  {
    id: 33,
    title: 'Shyvanna',
    category: 'Fighters',
    img: '/images/RiotX_ChampionList_shyvana.jpg',
  },
  {
    id: 34,
    title: 'Syndra',
    category: 'Mages',
    img: '/images/RiotX_ChampionList_syndra.jpg',
  },
  {
    id: 35,
    title: 'Thresh',
    category: 'Supporters',
    img: '/images/RiotX_ChampionList_thresh.jpg',
  },
  {
    id: 36,
    title: 'Urgot',
    category: 'Tanks',
    img: '/images/RiotX_ChampionList_urgot.jpg',
  },
  {
    id: 37,
    title: 'Vayne',
    category: 'Shooters',
    img: '/images/RiotX_ChampionList_vayne.jpg',
  },
  {
    id: 38,
    title: 'Vi',
    category: 'Fighters',
    img: '/images/RiotX_ChampionList_vi.jpg',
  },
  {
    id: 39,
    title: 'Vladimir',
    category: 'Mages',
    img: '/images/RiotX_ChampionList_vladimir.jpg',
  },
];

export default data;